# Generated by Django 5.2.4 on 2025-07-31 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrcet', '0002_student_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student',
            new_name='Csd',
        ),
    ]
